use std::path::Path;

use anyhow::{Context, Result};
use async_trait::async_trait;
use chrono::{DateTime, Utc};
use sqlx::Row;

use crate::store::sqlite::{PoolRef, open_pool};
use crate::subagent::{SubagentRun, SubagentStatus};

use super::SubagentStore;

/// SQLite-backed [`SubagentStore`] implementation.
///
/// Shares `tact.db` with the session / task / background stores. Schema:
///
/// - `subagent_runs(child_id, status, summary, started_at, finished_at)` —
///   `child_id` is the child session id (a UUID generated by
///   `spawn_subagent`), `status` is CHECK-constrained to
///   `running` / `completed` / `failed` / `cancelled`, timestamps are epoch
///   millis.
pub struct SqliteSubagentStore {
    pool: PoolRef,
}

impl SqliteSubagentStore {
    pub async fn new(path: &Path) -> Result<Self> {
        let pool = open_pool(path).await?;

        sqlx::query(
            r#"
            CREATE TABLE IF NOT EXISTS subagent_runs (
                child_id    TEXT    PRIMARY KEY,
                status      TEXT    NOT NULL
                            CHECK (status IN ('running','completed','failed','cancelled')),
                summary     TEXT,
                started_at  INTEGER NOT NULL,
                finished_at INTEGER
            );
            "#,
        )
        .execute(&*pool)
        .await
        .context("failed to create subagent_runs table")?;

        sqlx::query(
            "CREATE INDEX IF NOT EXISTS idx_subagent_runs_status ON subagent_runs(status);",
        )
        .execute(&*pool)
        .await
        .context("failed to create subagent_runs status index")?;

        sqlx::query(
            "CREATE INDEX IF NOT EXISTS idx_subagent_runs_started_at ON subagent_runs(started_at);",
        )
        .execute(&*pool)
        .await
        .context("failed to create subagent_runs started_at index")?;

        Ok(Self { pool })
    }
}

fn status_to_str(status: SubagentStatus) -> &'static str {
    match status {
        SubagentStatus::Running => "running",
        SubagentStatus::Completed => "completed",
        SubagentStatus::Failed => "failed",
        SubagentStatus::Cancelled => "cancelled",
    }
}

fn str_to_status(s: &str) -> Result<SubagentStatus> {
    match s {
        "running" => Ok(SubagentStatus::Running),
        "completed" => Ok(SubagentStatus::Completed),
        "failed" => Ok(SubagentStatus::Failed),
        "cancelled" => Ok(SubagentStatus::Cancelled),
        other => anyhow::bail!("invalid subagent status in database: {other}"),
    }
}

fn from_millis(millis: i64) -> DateTime<Utc> {
    DateTime::from_timestamp_millis(millis).unwrap_or_else(Utc::now)
}

fn row_to_run(row: &sqlx::sqlite::SqliteRow) -> Result<SubagentRun> {
    Ok(SubagentRun {
        child_id: row.try_get("child_id")?,
        status: str_to_status(&row.try_get::<String, _>("status")?)?,
        summary: row.try_get::<Option<String>, _>("summary")?,
        started_at: from_millis(row.try_get("started_at")?),
        finished_at: row
            .try_get::<Option<i64>, _>("finished_at")?
            .map(from_millis),
    })
}

#[async_trait]
impl SubagentStore for SqliteSubagentStore {
    async fn upsert(&self, record: &SubagentRun) -> Result<()> {
        sqlx::query(
            r#"
            INSERT INTO subagent_runs
                (child_id, status, summary, started_at, finished_at)
            VALUES (?, ?, ?, ?, ?)
            ON CONFLICT(child_id) DO UPDATE SET
                status      = excluded.status,
                summary     = excluded.summary,
                started_at  = excluded.started_at,
                finished_at = excluded.finished_at
            "#,
        )
        .bind(&record.child_id)
        .bind(status_to_str(record.status))
        .bind(&record.summary)
        .bind(record.started_at.timestamp_millis())
        .bind(record.finished_at.map(|dt| dt.timestamp_millis()))
        .execute(&*self.pool)
        .await
        .context("failed to upsert subagent run")?;
        Ok(())
    }

    async fn get(&self, id: &str) -> Result<Option<SubagentRun>> {
        let row = sqlx::query(
            "SELECT child_id, status, summary, started_at, finished_at
             FROM subagent_runs WHERE child_id = ?",
        )
        .bind(id)
        .fetch_optional(&*self.pool)
        .await?;
        row.map(|row| row_to_run(&row)).transpose()
    }

    async fn list(&self) -> Result<Vec<SubagentRun>> {
        let rows = sqlx::query(
            "SELECT child_id, status, summary, started_at, finished_at
             FROM subagent_runs ORDER BY started_at",
        )
        .fetch_all(&*self.pool)
        .await?;
        rows.iter().map(row_to_run).collect()
    }

    async fn list_running(&self) -> Result<Vec<SubagentRun>> {
        let rows = sqlx::query(
            "SELECT child_id, status, summary, started_at, finished_at
             FROM subagent_runs WHERE status = 'running' ORDER BY started_at",
        )
        .fetch_all(&*self.pool)
        .await?;
        rows.iter().map(row_to_run).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_db(name: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!("tact-subagentstore-test-{name}"));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir.join("tact.db")
    }

    fn record(id: &str, status: SubagentStatus) -> SubagentRun {
        SubagentRun {
            child_id: id.to_string(),
            status,
            summary: None,
            started_at: Utc::now(),
            finished_at: None,
        }
    }

    #[tokio::test]
    async fn upsert_get_round_trips_all_statuses() {
        let db = temp_db("round_trip");
        let store = SqliteSubagentStore::new(&db).await.unwrap();

        let mut r = record("00000001", SubagentStatus::Running);
        store.upsert(&r).await.unwrap();
        assert_eq!(
            store.get("00000001").await.unwrap().unwrap().status,
            SubagentStatus::Running
        );

        r.status = SubagentStatus::Completed;
        r.summary = Some("done".to_string());
        r.finished_at = Some(Utc::now());
        store.upsert(&r).await.unwrap();
        let got = store.get("00000001").await.unwrap().unwrap();
        assert_eq!(got.status, SubagentStatus::Completed);
        assert_eq!(got.summary.as_deref(), Some("done"));
        assert!(got.finished_at.is_some());
    }

    #[tokio::test]
    async fn get_unknown_id_returns_none() {
        let db = temp_db("unknown_id");
        let store = SqliteSubagentStore::new(&db).await.unwrap();
        assert!(store.get("deadbeef").await.unwrap().is_none());
    }

    #[tokio::test]
    async fn list_running_only_returns_running_rows() {
        let db = temp_db("list_running");
        let store = SqliteSubagentStore::new(&db).await.unwrap();

        store
            .upsert(&record("a", SubagentStatus::Running))
            .await
            .unwrap();
        store
            .upsert(&record("b", SubagentStatus::Completed))
            .await
            .unwrap();
        store
            .upsert(&record("c", SubagentStatus::Failed))
            .await
            .unwrap();
        store
            .upsert(&record("d", SubagentStatus::Cancelled))
            .await
            .unwrap();

        let running = store.list_running().await.unwrap();
        assert_eq!(running.len(), 1);
        assert_eq!(running[0].child_id, "a");
    }

    #[tokio::test]
    async fn store_is_persistent_across_reopen() {
        let db = temp_db("persistent");
        {
            let store = SqliteSubagentStore::new(&db).await.unwrap();
            store
                .upsert(&record("00000001", SubagentStatus::Failed))
                .await
                .unwrap();
        }
        let store = SqliteSubagentStore::new(&db).await.unwrap();
        let runs = store.list().await.unwrap();
        assert_eq!(runs.len(), 1);
        assert_eq!(runs[0].child_id, "00000001");
        assert_eq!(runs[0].status, SubagentStatus::Failed);
    }

    #[tokio::test]
    async fn list_is_sorted_by_started_at() {
        let db = temp_db("sorted");
        let store = SqliteSubagentStore::new(&db).await.unwrap();
        let mut later = record("00000002", SubagentStatus::Completed);
        later.started_at = Utc::now() + chrono::Duration::seconds(10);
        let mut earlier = record("00000001", SubagentStatus::Failed);
        earlier.started_at = Utc::now() - chrono::Duration::seconds(10);
        store.upsert(&later).await.unwrap();
        store.upsert(&earlier).await.unwrap();

        let runs = store.list().await.unwrap();
        assert_eq!(runs[0].child_id, "00000001");
        assert_eq!(runs[1].child_id, "00000002");
    }
}
