//! OpenAI-compatible LLM adapter.
//!
//! Uses `async-openai` types for request construction but handles responses
//! via custom deserialization structs in order to capture the
//! `reasoning_content` field, which `async-openai` does not expose in its
//! Chat Completions types (as of 0.40.2).
//!
//! SSE (Server-Sent Events) parsing uses `eventsource-stream` instead of
//! hand-rolled byte-level parsing, for correct handling of `\n\n` / `\r\n\r\n`
//! delimiters and connection lifecycle.

pub mod body;
pub(crate) mod compat;
pub mod multi_model;
pub mod responses;

pub use body::{BodyHookCtx, OpenAiBodyHook, StandardOpenAiBodyHook};
pub use multi_model::OpenAiMultiModelAdapter;

use crate::{ContentBlock, StopReason};
use async_openai::{
    config::Config,
    types::{
        ChatCompletionRequestMessage, ChatCompletionResponseFormat, ChatCompletionTool,
        ChatCompletionToolChoiceOption, Stop,
    },
};
use eventsource_stream::Eventsource;
use futures_util::StreamExt;
use reqwest::header::{AUTHORIZATION, HeaderMap};
use secrecy::{ExposeSecret, Secret};
use serde::Deserialize;
use serde::Serialize;
use std::{collections::HashMap, time::Duration};
use tokio::sync::mpsc::UnboundedSender;

use tact_protocol::{AgentUpdate, ThinkingChunk, TokenUsageInfo};

use super::LlmError;

/// Build UI events for one OpenAI-compatible stream delta.
///
/// Reasoning is always emitted before content so a single SSE chunk that carries
/// both fields still renders thinking above the answer.
fn openai_delta_ui_events(
    thinking_open: &mut bool,
    reasoning: Option<&str>,
    content: Option<&str>,
) -> Vec<AgentUpdate> {
    let mut events = Vec::new();
    if let Some(reasoning) = reasoning.filter(|s| !s.is_empty()) {
        if !*thinking_open {
            *thinking_open = true;
            events.push(AgentUpdate::ThinkingChunk(ThinkingChunk::Started));
        }
        events.push(AgentUpdate::ThinkingChunk(ThinkingChunk::Delta(
            reasoning.to_string(),
        )));
    }
    if let Some(content) = content.filter(|s| !s.is_empty()) {
        if *thinking_open {
            *thinking_open = false;
            events.push(AgentUpdate::ThinkingChunk(ThinkingChunk::Finished));
        }
        events.push(AgentUpdate::StreamChunk(content.to_string()));
    }
    events
}

fn finish_thinking_event(thinking_open: &mut bool) -> Option<AgentUpdate> {
    if !*thinking_open {
        return None;
    }
    *thinking_open = false;
    Some(AgentUpdate::ThinkingChunk(ThinkingChunk::Finished))
}

// ── Streaming response types ──────────────────────────────────────────

#[derive(Serialize)]
pub struct CreateChatCompletionRequest {
    /// A list of messages comprising the conversation so far. [Example Python code](https://cookbook.openai.com/examples/how_to_format_inputs_to_chatgpt_models).
    pub messages: Vec<ChatCompletionRequestMessage>, // min: 1

    /// ID of the model to use.
    /// See the [model endpoint compatibility](https://platform.openai.com/docs/models/model-endpoint-compatibility) table for details on which models work with the Chat API.
    pub model: String,

    /// Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.
    ///
    /// [See more information about frequency and presence penalties.](https://platform.openai.com/docs/api-reference/parameter-details)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub frequency_penalty: Option<f32>, // min: -2.0, max: 2.0, default: 0

    /// Modify the likelihood of specified tokens appearing in the completion.
    ///
    /// Accepts a json object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100.
    /// Mathematically, the bias is added to the logits generated by the model prior to sampling.
    /// The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection;
    /// values like -100 or 100 should result in a ban or exclusive selection of the relevant token.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logit_bias: Option<HashMap<String, serde_json::Value>>, // default: null

    /// Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output token returned in the `content` of `message`. This option is currently not available on the `gpt-4-vision-preview` model.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logprobs: Option<bool>,

    /// An integer between 0 and 5 specifying the number of most likely tokens to return at each token position, each with an associated log probability. `logprobs` must be set to `true` if this parameter is used.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub top_logprobs: Option<u8>,

    /// The maximum number of [tokens](https://platform.openai.com/tokenizer) that can be generated in the chat completion.
    ///
    /// The total length of input tokens and generated tokens is limited by the model's context length. [Example Python code](https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken) for counting tokens.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u16>,

    /// How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices. Keep `n` as `1` to minimize costs.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub n: Option<u8>, // min:1, max: 128, default: 1

    /// Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.
    ///
    /// [See more information about frequency and presence penalties.](https://platform.openai.com/docs/api-reference/parameter-details)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub presence_penalty: Option<f32>, // min: -2.0, max: 2.0, default 0

    /// An object specifying the format that the model must output. Compatible with [GPT-4 Turbo](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo) and all GPT-3.5 Turbo models newer than `gpt-3.5-turbo-1106`.
    ///
    /// Setting to `{ "type": "json_object" }` enables JSON mode, which guarantees the message the model generates is valid JSON.
    ///
    /// **Important:** when using JSON mode, you **must** also instruct the model to produce JSON yourself via a system or user message. Without this, the model may generate an unending stream of whitespace until the generation reaches the token limit, resulting in a long-running and seemingly "stuck" request. Also note that the message content may be partially cut off if `finish_reason="length"`, which indicates the generation exceeded `max_tokens` or the conversation exceeded the max context length.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub response_format: Option<ChatCompletionResponseFormat>,

    ///  This feature is in Beta.
    /// If specified, our system will make a best effort to sample deterministically, such that repeated requests
    /// with the same `seed` and parameters should return the same result.
    /// Determinism is not guaranteed, and you should refer to the `system_fingerprint` response parameter to monitor changes in the backend.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub seed: Option<i64>,

    /// Up to 4 sequences where the API will stop generating further tokens.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stop: Option<Stop>,

    /// If set, partial message deltas will be sent, like in ChatGPT.
    /// Tokens will be sent as data-only [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format)
    /// as they become available, with the stream terminated by a `data: [DONE]` message. [Example Python code](https://cookbook.openai.com/examples/how_to_stream_completions).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>,

    // `stream_options` is absent from async-openai 0.20's
    // CreateChatCompletionRequest, so we inject it into the JSON body.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stream_options: Option<StreamOptions>,

    /// What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random,
    /// while lower values like 0.2 will make it more focused and deterministic.
    ///
    /// We generally recommend altering this or `top_p` but not both.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f32>, // min: 0, max: 2, default: 1,

    /// An alternative to sampling with temperature, called nucleus sampling,
    /// where the model considers the results of the tokens with top_p probability mass.
    /// So 0.1 means only the tokens comprising the top 10% probability mass are considered.
    ///
    ///  We generally recommend altering this or `temperature` but not both.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub top_p: Option<f32>, // min: 0, max: 1, default: 1

    /// A list of tools the model may call. Currently, only functions are supported as a tool.
    /// Use this to provide a list of functions the model may generate JSON inputs for.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<ChatCompletionTool>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_choice: Option<ChatCompletionToolChoiceOption>,

    /// A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](https://platform.openai.com/docs/guides/safety-best-practices/end-user-ids).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
}

#[derive(Copy, Clone, Serialize)]
pub struct StreamOptions {
    pub include_usage: Option<bool>,
}

/// Default streaming options — request token usage in the final chunk.
pub(crate) const STREAM_OPTIONS_WITH_USAGE: StreamOptions = StreamOptions {
    include_usage: Some(true),
};

/// Top-level SSE chunk from an OpenAI-compatible streaming chat completion.
#[derive(Debug, Default, Deserialize)]
#[serde(default)]
struct StreamChunk {
    choices: Vec<StreamChoice>,
    usage: Option<StreamUsage>,
}

#[derive(Debug, Default, Deserialize)]
#[serde(default)]
struct StreamChoice {
    delta: StreamDelta,
    finish_reason: Option<String>,
}

#[derive(Debug, Default, Deserialize)]
#[serde(default)]
struct StreamDelta {
    content: Option<String>,
    #[serde(rename = "reasoning_content")]
    reasoning_content: Option<String>,
    tool_calls: Vec<StreamToolCallDelta>,
}

#[derive(Debug, Deserialize)]
struct StreamToolCallDelta {
    index: u32,
    id: Option<String>,
    function: Option<StreamFunctionDelta>,
}

#[derive(Debug, Deserialize)]
struct StreamFunctionDelta {
    name: Option<String>,
    arguments: Option<String>,
}

#[derive(Debug, Deserialize)]
struct StreamUsage {
    prompt_tokens: u32,
    completion_tokens: u32,
    /// DeepSeek returns `total_tokens` directly; fall back to prompt+completion.
    total_tokens: Option<u32>,
    prompt_cache_hit_tokens: Option<u32>,
    prompt_cache_miss_tokens: Option<u32>,
    completion_tokens_details: Option<StreamCompletionTokensDetails>,
}

#[derive(Debug, Deserialize)]
struct StreamCompletionTokensDetails {
    reasoning_tokens: Option<u32>,
}

/// Map Anthropic-style `thinking.budget_tokens` to OpenAI `reasoning_effort`.
///
/// Internal config only exposes a token budget; Chat Completions for OpenAI
/// reasoning models expects an effort band instead. `None` means do not send
/// the field (thinking off / budget zero).
///
/// Bands (inclusive):
/// - `0` → omit
/// - `1..=10_000` → `low`
/// - `10_001..=32_000` → `medium`
/// - `> 32_000` → `high`
pub fn reasoning_effort_from_budget(budget_tokens: usize) -> Option<&'static str> {
    crate::effective_reasoning_effort(None, budget_tokens).map(crate::OpenAiReasoningEffort::as_str)
}

/// Resolve the current provider's explicit effort or the legacy budget bands.
pub fn current_reasoning_effort_from_budget(budget_tokens: usize) -> Option<&'static str> {
    crate::read_provider(|provider| {
        crate::effective_reasoning_effort(provider.reasoning_effort, budget_tokens)
            .map(crate::OpenAiReasoningEffort::as_str)
    })
}

fn tool_use_block_from_parts(
    id: Option<String>,
    name: Option<String>,
    args: String,
) -> Option<ContentBlock> {
    let id = id.filter(|id| !id.is_empty())?;
    let name = name.filter(|name| !name.is_empty())?;
    let input = serde_json::from_str(&args)
        .unwrap_or_else(|_| serde_json::Value::Object(Default::default()));
    Some(ContentBlock::ToolUse { id, name, input })
}

fn tool_use_block_from_response(id: &str, name: &str, args: &str) -> Option<ContentBlock> {
    tool_use_block_from_parts(
        Some(id.to_string()),
        Some(name.to_string()),
        args.to_string(),
    )
}

// ── Config / Adapter ───────────────────────────────────────────────────

/// Custom config that strips the `OpenAI-Beta` header.
///
/// `async-openai`'s built-in `OpenAIConfig` unconditionally adds
/// `OpenAI-Beta: assistants=v1` to every request, which causes 403
/// on many OpenAI-compatible providers (Kimi, DeepSeek, etc.).
#[derive(Clone, Debug)]
pub struct CompatibleConfig {
    api_base: String,
    api_key: Secret<String>,
}

impl CompatibleConfig {
    pub fn new(api_key: impl Into<String>, api_base: impl Into<String>) -> Self {
        Self {
            api_base: api_base.into(),
            api_key: Secret::new(api_key.into()),
        }
    }
}

impl Config for CompatibleConfig {
    fn headers(&self) -> HeaderMap {
        let mut headers = HeaderMap::new();
        headers.insert(
            AUTHORIZATION,
            format!("Bearer {}", self.api_key.expose_secret())
                .parse()
                .unwrap(),
        );
        // Kimi's coding endpoint whitelists specific coding agents.
        // Without a matching User-Agent it returns 403 access_terminated_error.
        headers.insert(reqwest::header::USER_AGENT, "Claude Code".parse().unwrap());
        headers
    }

    fn url(&self, path: &str) -> String {
        format!("{}{}", self.api_base, path)
    }

    fn query(&self) -> Vec<(&str, &str)> {
        vec![]
    }

    fn api_base(&self) -> &str {
        &self.api_base
    }

    fn api_key(&self) -> &Secret<String> {
        &self.api_key
    }
}

/// HTTP transport for OpenAI-compatible Chat Completions.
///
/// Request shaping (provider-specific body fields) lives in
/// [`OpenAiMultiModelAdapter`] / [`OpenAiBodyHook`].
#[derive(Clone, Debug)]
pub struct OpenAiAdapter {
    config: CompatibleConfig,
    client: reqwest::Client,
}

/// Accumulates a streaming tool-call delta across SSE chunks.
struct PendingToolCall {
    id: Option<String>,
    name: Option<String>,
    args: String,
}

impl OpenAiAdapter {
    pub fn new(config: CompatibleConfig) -> Self {
        let client = reqwest::Client::builder()
            .read_timeout(Duration::from_secs(120))
            .build()
            .expect("failed to build reqwest client");
        Self { config, client }
    }

    /// Expose the configured API base URL for diagnostics/tests.
    pub fn base_url(&self) -> &str {
        self.config.api_base()
    }

    /// Stream a chat completion via SSE, capturing `reasoning_content`
    /// not present in `async-openai`'s response types.
    ///
    /// Uses `eventsource-stream` for robust SSE parsing (handles both
    /// `\n\n` and `\r\n\r\n` delimiters). Caller must set `stream` /
    /// `stream_options` on `body` when usage is required.
    pub async fn stream_completion(
        &self,
        body: &serde_json::Value,
        ui_tx: Option<UnboundedSender<AgentUpdate>>,
    ) -> Result<
        (
            Vec<ContentBlock>,
            Option<StopReason>,
            Option<TokenUsageInfo>,
            Option<crate::LlmRequestBody>,
        ),
        LlmError,
    > {
        let json_body = serde_json::to_vec(body).map_err(|e| LlmError::Other(e.to_string()))?;

        let url = self.config.url("/chat/completions");
        let headers = self.config.headers();

        let response = self
            .client
            .post(&url)
            .headers(headers)
            .json(body)
            .send()
            .await
            .map_err(|e| LlmError::Other(e.to_string()))?;

        // Read the full response body on non-2xx so the actual API error
        // message is surfaced, not just the HTTP status code.
        if !response.status().is_success() {
            let status = response.status();
            let resp_body = response
                .text()
                .await
                .unwrap_or_else(|e| format!("<failed to read response body: {e}>"));
            tracing::debug!(
                status = %status,
                response_body = %resp_body,
                request_body = %String::from_utf8_lossy(&json_body),
                "LLM HTTP request failed"
            );
            return Err(LlmError::Other(format!("http {status}: {resp_body}")));
        }

        let mut event_stream = response.bytes_stream().eventsource();

        let mut text_buffer = String::new();
        let mut reasoning_buffer = String::new();
        // Buffer tool call results until the final chunk is received.
        // (vec of (id, name, args) buffers)
        let mut tool_call_buffers: Vec<PendingToolCall> = Vec::new();
        let mut stop_reason: Option<StopReason> = None;
        let mut token_usage: Option<TokenUsageInfo> = None;
        // OpenAI-compatible streams only expose reasoning deltas — synthesize
        // Started / Finished around the first and last reasoning fragment.
        let mut thinking_open = false;

        while let Some(event) = event_stream.next().await {
            match event {
                Err(e) => {
                    tracing::debug!(
                        error = %e,
                        request_body = %String::from_utf8_lossy(&json_body),
                        "SSE stream failed; logging request body for diagnostics"
                    );
                    return Err(LlmError::Other(format!("SSE error: {e}")));
                }
                Ok(msg) => {
                    if msg.data == "[DONE]" {
                        break;
                    }

                    let chunk: StreamChunk = serde_json::from_str(&msg.data)
                        .map_err(|e| LlmError::Other(format!("JSON parse: {e}")))?;

                    // ── choices ──
                    for choice in &chunk.choices {
                        let delta = &choice.delta;

                        for event in openai_delta_ui_events(
                            &mut thinking_open,
                            delta.reasoning_content.as_deref(),
                            delta.content.as_deref(),
                        ) {
                            match &event {
                                AgentUpdate::StreamChunk(content) => {
                                    text_buffer.push_str(content);
                                }
                                AgentUpdate::ThinkingChunk(ThinkingChunk::Delta(reasoning)) => {
                                    reasoning_buffer.push_str(reasoning);
                                }
                                _ => {}
                            }
                            if let Some(ref tx) = ui_tx {
                                let _ = tx.send(event);
                            }
                        }

                        // tool_calls
                        if !delta.tool_calls.is_empty()
                            && let Some(finished) = finish_thinking_event(&mut thinking_open)
                            && let Some(ref tx) = ui_tx
                        {
                            let _ = tx.send(finished);
                        }
                        for tc in &delta.tool_calls {
                            let idx = tc.index as usize;
                            while tool_call_buffers.len() <= idx {
                                tool_call_buffers.push(PendingToolCall {
                                    id: None,
                                    name: None,
                                    args: String::new(),
                                });
                            }
                            if let Some(ref id) = tc.id {
                                tool_call_buffers[idx].id = Some(id.clone());
                            }
                            if let Some(ref func) = tc.function {
                                if let Some(ref name) = func.name {
                                    tool_call_buffers[idx].name = Some(name.clone());
                                }
                                if let Some(ref args) = func.arguments {
                                    tool_call_buffers[idx].args.push_str(args);
                                }
                            }
                        }

                        // finish_reason
                        if let Some(ref finish) = choice.finish_reason {
                            stop_reason = StopReason::from_openai(Some(finish.as_str()));
                        }
                    }

                    // ── usage (sent in final chunk when stream_options.include_usage is set) ──
                    if let Some(usage) = &chunk.usage {
                        // Only emit when there are real token counts.
                        if usage.prompt_tokens > 0 || usage.completion_tokens > 0 {
                            let cache_hit = usage.prompt_cache_hit_tokens.unwrap_or(0);
                            let cache_miss = usage.prompt_cache_miss_tokens.unwrap_or(0);
                            let reasoning = usage
                                .completion_tokens_details
                                .as_ref()
                                .and_then(|d| d.reasoning_tokens)
                                .unwrap_or(0);
                            let info = TokenUsageInfo {
                                prompt: usage.prompt_tokens,
                                completion: usage.completion_tokens,
                                total: usage
                                    .total_tokens
                                    .unwrap_or(usage.prompt_tokens + usage.completion_tokens),
                                prompt_cache_hit_tokens: cache_hit,
                                prompt_cache_miss_tokens: cache_miss,
                                reasoning_tokens: reasoning,
                            };
                            if let Some(ref tx) = ui_tx {
                                let _ = tx.send(AgentUpdate::TokenUsage(info.clone()));
                            }
                            token_usage = Some(info);
                        }
                    }
                }
            }
        }

        if let Some(finished) = finish_thinking_event(&mut thinking_open)
            && let Some(ref tx) = ui_tx
        {
            let _ = tx.send(finished);
        }

        // Build response blocks
        let mut response_blocks = Vec::new();
        if !reasoning_buffer.is_empty() {
            response_blocks.push(ContentBlock::Thinking {
                thinking: reasoning_buffer,
                signature: String::new(),
            });
        }
        if !text_buffer.is_empty() {
            response_blocks.push(ContentBlock::Text { text: text_buffer });
        }
        // use tool call buffers
        for PendingToolCall { id, name, args } in tool_call_buffers {
            if let Some(block) = tool_use_block_from_parts(id, name, args) {
                response_blocks.push(block);
            }
        }

        Ok((response_blocks, stop_reason, token_usage, Some(json_body)))
    }

    /// Non-streaming chat completion against a finished JSON body.
    pub async fn create_completion(
        &self,
        body: &serde_json::Value,
    ) -> Result<
        (
            Vec<ContentBlock>,
            Option<StopReason>,
            Option<TokenUsageInfo>,
            Option<crate::LlmRequestBody>,
        ),
        LlmError,
    > {
        let json_body = serde_json::to_vec(body).map_err(|e| LlmError::Other(e.to_string()))?;

        let url = self.config.url("/chat/completions");
        let headers = self.config.headers();

        let response = self
            .client
            .post(&url)
            .headers(headers)
            .json(body)
            .send()
            .await
            .map_err(|e| LlmError::Other(e.to_string()))?;

        if !response.status().is_success() {
            let status = response.status();
            let resp_body = response.text().await.unwrap_or_default();
            return Err(LlmError::Other(format!("HTTP {status}: {resp_body}")));
        }

        let json: serde_json::Value = response
            .json()
            .await
            .map_err(|e| LlmError::Other(e.to_string()))?;

        let choice = json["choices"]
            .as_array()
            .and_then(|a| a.first())
            .ok_or_else(|| LlmError::Other("No choices in response".to_string()))?;

        let message = &choice["message"];
        let mut blocks = Vec::new();

        // reasoning_content
        if let Some(reasoning) = message["reasoning_content"].as_str()
            && !reasoning.is_empty()
        {
            blocks.push(ContentBlock::Thinking {
                thinking: reasoning.to_string(),
                signature: String::new(),
            });
        }

        // content
        if let Some(content) = message["content"].as_str() {
            blocks.push(ContentBlock::Text {
                text: content.to_string(),
            });
        }

        // tool_calls
        if let Some(tool_calls) = message["tool_calls"].as_array() {
            for tc in tool_calls {
                let id = tc["id"].as_str().unwrap_or("");
                let name = tc["function"]["name"].as_str().unwrap_or("");
                let args = tc["function"]["arguments"].as_str().unwrap_or("{}");
                if let Some(block) = tool_use_block_from_response(id, name, args) {
                    blocks.push(block);
                }
            }
        }

        let stop_reason = StopReason::from_openai(choice["finish_reason"].as_str());

        let token_usage = json["usage"].as_object().map(|u| {
            let prompt = u["prompt_tokens"].as_u64().unwrap_or(0) as u32;
            let completion = u["completion_tokens"].as_u64().unwrap_or(0) as u32;
            TokenUsageInfo {
                prompt,
                completion,
                total: u["total_tokens"]
                    .as_u64()
                    .map(|n| n as u32)
                    .unwrap_or(prompt + completion),
                prompt_cache_hit_tokens: u["prompt_cache_hit_tokens"]
                    .as_u64()
                    .map(|n| n as u32)
                    .unwrap_or(0),
                prompt_cache_miss_tokens: u["prompt_cache_miss_tokens"]
                    .as_u64()
                    .map(|n| n as u32)
                    .unwrap_or(0),
                reasoning_tokens: u["completion_tokens_details"]
                    .get("reasoning_tokens")
                    .and_then(|v| v.as_u64())
                    .map(|n| n as u32)
                    .unwrap_or(0),
            }
        });

        Ok((blocks, stop_reason, token_usage, Some(json_body)))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reasoning_effort_bands_from_budget() {
        assert_eq!(reasoning_effort_from_budget(0), None);
        assert_eq!(reasoning_effort_from_budget(1), Some("low"));
        assert_eq!(reasoning_effort_from_budget(10_000), Some("low"));
        assert_eq!(reasoning_effort_from_budget(10_001), Some("medium"));
        assert_eq!(reasoning_effort_from_budget(32_000), Some("medium"));
        assert_eq!(reasoning_effort_from_budget(32_001), Some("high"));
    }

    #[test]
    fn tool_use_block_from_parts_skips_empty_slots() {
        assert!(tool_use_block_from_parts(None, Some("read_file".into()), "{}".into()).is_none());
        assert!(tool_use_block_from_parts(Some("call_1".into()), None, "{}".into()).is_none());
        assert!(
            tool_use_block_from_parts(Some("".into()), Some("read_file".into()), "{}".into())
                .is_none()
        );

        let block = tool_use_block_from_parts(
            Some("call_1".into()),
            Some("read_file".into()),
            r#"{"path":"a.rs"}"#.into(),
        )
        .expect("valid tool call");
        assert!(matches!(block, ContentBlock::ToolUse { .. }));
    }

    #[test]
    fn openai_delta_emits_started_delta_then_finished_before_content() {
        let mut open = false;
        let events = openai_delta_ui_events(&mut open, Some("reason"), Some("answer"));
        assert!(matches!(
            events.as_slice(),
            [
                AgentUpdate::ThinkingChunk(ThinkingChunk::Started),
                AgentUpdate::ThinkingChunk(ThinkingChunk::Delta(r)),
                AgentUpdate::ThinkingChunk(ThinkingChunk::Finished),
                AgentUpdate::StreamChunk(c),
            ] if r == "reason" && c == "answer"
        ));
        assert!(!open);
    }

    #[test]
    fn openai_delta_reasoning_only_leaves_thinking_open() {
        let mut open = false;
        let events = openai_delta_ui_events(&mut open, Some("think"), None);
        assert!(matches!(
            events.as_slice(),
            [
                AgentUpdate::ThinkingChunk(ThinkingChunk::Started),
                AgentUpdate::ThinkingChunk(ThinkingChunk::Delta(r)),
            ] if r == "think"
        ));
        assert!(open);
        let finished = finish_thinking_event(&mut open);
        assert!(matches!(
            finished,
            Some(AgentUpdate::ThinkingChunk(ThinkingChunk::Finished))
        ));
        assert!(!open);
        assert!(finish_thinking_event(&mut open).is_none());
    }

    #[test]
    fn openai_delta_content_after_open_thinking_finishes_once() {
        let mut open = true;
        let events = openai_delta_ui_events(&mut open, None, Some("done"));
        assert!(matches!(
            events.as_slice(),
            [
                AgentUpdate::ThinkingChunk(ThinkingChunk::Finished),
                AgentUpdate::StreamChunk(c),
            ] if c == "done"
        ));
        assert!(!open);
    }

    #[test]
    fn openai_delta_skips_empty_fields() {
        let mut open = false;
        let events = openai_delta_ui_events(&mut open, Some(""), Some(""));
        assert!(events.is_empty());
        assert!(!open);
    }
}
